(require 'g-emacs-comm)
(require 'g-evil)
(require 'g-smex)
(require 'g-company)
(require 'g-smartparens)
(require 'g-evil-leader)
(require 'g-org)
(require 'g-dired)
(require 'g-theme)
(require 'g-hungry-delete)
(require 'g-c-common-mode)
(require 'g-projectile)
(require 'g-neotree)
;; (require 'g-ggtags)
(require 'g-function-args)
(require 'g-smooth-scrolling)
(require 'g-popwin)
(require 'g-indent-region)
(require 'g-powerline)
(require 'g-window-numbering)
(require 'g-powerline-evil)
(require 'g-nyan-mode)
(require 'g-which-key)
(require 'g-expand-region)
(require 'g-rainbow-delimiters)



(provide 'g-config)
